In [1]:
import numpy as np

In [2]:
arr = np.array([[10, 20,30],
                [40, 50, 60],
                [70, 80, 90]])

In [3]:
print(arr[0, 1])   # 20 (row 0, col 1)
print(arr[2, 2])   # 90 (row 2, col 2)

20
90


In [4]:
print(arr[-1, -2])  # 80 (last row, 2nd last column)
print(arr[-3, -3])  # 10 (first row, first column)

80
10


In [5]:
# General form: arr[start:stop:step]
print(arr[0:2, 1:3])   # rows 0-1, cols 1-2

[[20 30]
 [50 60]]


In [6]:
print(arr[::2, ::2])   # every 2nd row & 2nd column

[[10 30]
 [70 90]]


In [7]:
slice_arr = arr[0, :2]   # view (not a copy)
slice_arr[0] = 999

In [8]:
print(arr[0])            # original changes

[999  20  30]


In [9]:
copy_arr = arr[1].copy() # independent copy
copy_arr[0] = 555

In [10]:
print(arr[1])            # original unchanged

[40 50 60]


In [ ]:
# Random generator with seed (reproducibility)
rng = np.random.default_rng(seed=42)
nums = rng.integers(1, 10, size=5)

In [ ]:
print(nums)